name = "gitflare-sinameraji--kimiflare"
main = "src/index.tsx"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
account_id = "b35e975c549e4e6b888ed6a6d436d89f"

[[artifacts]]
binding = "ARTIFACTS"
namespace = "gitflare"

[[durable_objects.bindings]]
name = "REPO"
class_name = "RepoDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RepoDO"]

[vars]
GITFLARE_VERSION = "0.0.0"
REPO_MAP = "{\"sinameraji/kimiflare\":{\"name\":\"sinameraji--kimiflare\",\"remote\":\"https://b35e975c549e4e6b888ed6a6d436d89f.artifacts.cloudflare.net/git/gitflare/sinameraji--kimiflare.git\"}}"
